//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalFolders.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_es_419 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_es_419() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalFolders.Properties.Resources.es-419", typeof(Resources_es_419).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de:.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ancelar.
        /// </summary>
        public static string ancel {
            get {
                return ResourceManager.GetString("ancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicando....
        /// </summary>
        public static string Applying {
            get {
                return ResourceManager.GetString("Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar subcarpetas.
        /// </summary>
        public static string ApplySubfolders {
            get {
                return ResourceManager.GetString("ApplySubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicación para personalizar los iconos de tus carpetas en segundos.
        /// </summary>
        public static string AppToCustomizeFolderIcons {
            get {
                return ResourceManager.GetString("AppToCustomizeFolderIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar Portables.
        /// </summary>
        public static string AutoApply {
            get {
                return ResourceManager.GetString("AutoApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🢔🢔   Regresar.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambios.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Tema....
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir....
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir Icono.
        /// </summary>
        public static string ChooseIcon {
            get {
                return ResourceManager.GetString("ChooseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar a portable.
        /// </summary>
        public static string ConfigureAsPortable {
            get {
                return ResourceManager.GetString("ConfigureAsPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estaurar.
        /// </summary>
        public static string estore {
            get {
                return ResourceManager.GetString("estore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icono externo (No Portable).
        /// </summary>
        public static string ExternalIconTooltip {
            get {
                return ResourceManager.GetString("ExternalIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpetas.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus carpetas han sido personalizadas. Si no hay cambios, actualiza la ventana y/o escritorio..
        /// </summary>
        public static string FoldersHaveBeenCustomized {
            get {
                return ResourceManager.GetString("FoldersHaveBeenCustomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus carpetas se han restaurado correctamente..
        /// </summary>
        public static string FoldersHaveBeenRestored {
            get {
                return ResourceManager.GetString("FoldersHaveBeenRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  carpetas se han omitido porque no se permite personalizarlas..
        /// </summary>
        public static string FoldersHaveBeenSkipped {
            get {
                return ResourceManager.GetString("FoldersHaveBeenSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icono.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icono dentro de la Carpeta.
        /// </summary>
        public static string IconOnFolderToolTip {
            get {
                return ResourceManager.GetString("IconOnFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iconos.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir subcarpetas.
        /// </summary>
        public static string IncludeSubfolders {
            get {
                return ResourceManager.GetString("IncludeSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funciona arrastrando carpetas al panel izquierdo sin marcar ninguna casilla, de lo contrario este switch no podrá activarse..
        /// </summary>
        public static string ItWorksByDraggingFolders {
            get {
                return ResourceManager.GetString("ItWorksByDraggingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma: English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma: Español.
        /// </summary>
        public static string LanguageEspañol {
            get {
                return ResourceManager.GetString("LanguageEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente   🢖🢖.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La configuración portable solo permite menos de 30 carpetas..
        /// </summary>
        public static string OnlyAllowsLessThan30Folders {
            get {
                return ResourceManager.GetString("OnlyAllowsLessThan30Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups, no se pueden agregar las carpetas. Por favor, arrástralas y suéltalas en la app..
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones:.
        /// </summary>
        public static string OptionsAbout {
            get {
                return ResourceManager.GetString("OptionsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, espera....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icono Portable dentro de la Carpeta.
        /// </summary>
        public static string PortableOnFolderToolTip {
            get {
                return ResourceManager.GetString("PortableOnFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plicar.
        /// </summary>
        public static string pply {
            get {
                return ResourceManager.GetString("pply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar de portable.
        /// </summary>
        public static string RestoreFromPortable {
            get {
                return ResourceManager.GetString("RestoreFromPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar subcarpetas.
        /// </summary>
        public static string RestoreSubfolders {
            get {
                return ResourceManager.GetString("RestoreSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son más de 600 carpetas. ¿Realmente quieres continuar?.
        /// </summary>
        public static string ThereAreMoreThan600Folders {
            get {
                return ResourceManager.GetString("ThereAreMoreThan600Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demasiadas carpetas.
        /// </summary>
        public static string TooManyFolders {
            get {
                return ResourceManager.GetString("TooManyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ersonalizar.
        /// </summary>
        public static string ustomize {
            get {
                return ResourceManager.GetString("ustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver icono en cualquier PC.
        /// </summary>
        public static string ViewIconOnAnyPC {
            get {
                return ResourceManager.GetString("ViewIconOnAnyPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar a portable   hará que el icono personalizado sea visible en cualquier otra PC..
        /// </summary>
        public static string WillMakeTheCustomIconVisible {
            get {
                return ResourceManager.GetString("WillMakeTheCustomIconVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar de portable   eliminará cualquier icono que se haya copiado dentro de la carpeta que fue configurada como portable..
        /// </summary>
        public static string WillRemoveAnyIconsCopied {
            get {
                return ResourceManager.GetString("WillRemoveAnyIconsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debido a que el icono se copiará (oculto) dentro de cada carpeta, hay un límite para personalizar el cual es hasta 30..
        /// </summary>
        public static string YouCanCustomizeUpTo30Folders {
            get {
                return ResourceManager.GetString("YouCanCustomizeUpTo30Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes restaurar hasta 30 carpetas a la vez, el cual era el limite..
        /// </summary>
        public static string YouCanRestoreUpTo30Folders {
            get {
                return ResourceManager.GetString("YouCanRestoreUpTo30Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus carpetas se están personalizando..
        /// </summary>
        public static string YourFoldersAreBeingCustomized {
            get {
                return ResourceManager.GetString("YourFoldersAreBeingCustomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus carpetas se están restaurando..
        /// </summary>
        public static string YourFoldersAreBeingRestored {
            get {
                return ResourceManager.GetString("YourFoldersAreBeingRestored", resourceCulture);
            }
        }
    }
}
