//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalFolders.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalFolders.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About:.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ancel.
        /// </summary>
        public static string ancel {
            get {
                return ResourceManager.GetString("ancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying....
        /// </summary>
        public static string Applying {
            get {
                return ResourceManager.GetString("Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Subfolders.
        /// </summary>
        public static string ApplySubfolders {
            get {
                return ResourceManager.GetString("ApplySubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application to customize your folder icons in a few seconds.
        /// </summary>
        public static string AppToCustomizeFolderIcons {
            get {
                return ResourceManager.GetString("AppToCustomizeFolderIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Portables.
        /// </summary>
        public static string AutoApply {
            get {
                return ResourceManager.GetString("AutoApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🢔🢔   Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme....
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Icon.
        /// </summary>
        public static string ChooseIcon {
            get {
                return ResourceManager.GetString("ChooseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure as portable.
        /// </summary>
        public static string ConfigureAsPortable {
            get {
                return ResourceManager.GetString("ConfigureAsPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estore.
        /// </summary>
        public static string estore {
            get {
                return ResourceManager.GetString("estore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Icon (Non Portable).
        /// </summary>
        public static string ExternalIconTooltip {
            get {
                return ResourceManager.GetString("ExternalIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your folders have been customized. If there are no changes, refresh the window and/or desktop..
        /// </summary>
        public static string FoldersHaveBeenCustomized {
            get {
                return ResourceManager.GetString("FoldersHaveBeenCustomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your folders have been restored successfully..
        /// </summary>
        public static string FoldersHaveBeenRestored {
            get {
                return ResourceManager.GetString("FoldersHaveBeenRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  folders have been skipped because customization is not allowed..
        /// </summary>
        public static string FoldersHaveBeenSkipped {
            get {
                return ResourceManager.GetString("FoldersHaveBeenSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon inside Folder.
        /// </summary>
        public static string IconOnFolderToolTip {
            get {
                return ResourceManager.GetString("IconOnFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subfolders.
        /// </summary>
        public static string IncludeSubfolders {
            get {
                return ResourceManager.GetString("IncludeSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It works by dragging folders to the left panel without checking any checkbox, otherwise this switch will not be able to turn on..
        /// </summary>
        public static string ItWorksByDraggingFolders {
            get {
                return ResourceManager.GetString("ItWorksByDraggingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: Español.
        /// </summary>
        public static string LanguageEspañol {
            get {
                return ResourceManager.GetString("LanguageEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next   🢖🢖.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable configuration only allows less than 30 folders..
        /// </summary>
        public static string OnlyAllowsLessThan30Folders {
            get {
                return ResourceManager.GetString("OnlyAllowsLessThan30Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, folders can&apos;t be added. Please drag and drop them into the app..
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        public static string OptionsAbout {
            get {
                return ResourceManager.GetString("OptionsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Icon inside Folder.
        /// </summary>
        public static string PortableOnFolderToolTip {
            get {
                return ResourceManager.GetString("PortableOnFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pply.
        /// </summary>
        public static string pply {
            get {
                return ResourceManager.GetString("pply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore from portable.
        /// </summary>
        public static string RestoreFromPortable {
            get {
                return ResourceManager.GetString("RestoreFromPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore subfolders.
        /// </summary>
        public static string RestoreSubfolders {
            get {
                return ResourceManager.GetString("RestoreSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than 600 folders. Do you really want to continue?.
        /// </summary>
        public static string ThereAreMoreThan600Folders {
            get {
                return ResourceManager.GetString("ThereAreMoreThan600Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many folders.
        /// </summary>
        public static string TooManyFolders {
            get {
                return ResourceManager.GetString("TooManyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ustomize.
        /// </summary>
        public static string ustomize {
            get {
                return ResourceManager.GetString("ustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.0.
        /// </summary>
        public static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View icon on any PC.
        /// </summary>
        public static string ViewIconOnAnyPC {
            get {
                return ResourceManager.GetString("ViewIconOnAnyPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure as portable   will make the custom icon visible on any other PC..
        /// </summary>
        public static string WillMakeTheCustomIconVisible {
            get {
                return ResourceManager.GetString("WillMakeTheCustomIconVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore from portable   will remove any icons that have been copied into the folder that was configured as portable..
        /// </summary>
        public static string WillRemoveAnyIconsCopied {
            get {
                return ResourceManager.GetString("WillRemoveAnyIconsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because the icon will be copied (hidden) within each folder, there is a limit to customize which is up to 30..
        /// </summary>
        public static string YouCanCustomizeUpTo30Folders {
            get {
                return ResourceManager.GetString("YouCanCustomizeUpTo30Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can restore up to 30 folders at a time, which was the limit..
        /// </summary>
        public static string YouCanRestoreUpTo30Folders {
            get {
                return ResourceManager.GetString("YouCanRestoreUpTo30Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your folders are being customized..
        /// </summary>
        public static string YourFoldersAreBeingCustomized {
            get {
                return ResourceManager.GetString("YourFoldersAreBeingCustomized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your folders are being restored..
        /// </summary>
        public static string YourFoldersAreBeingRestored {
            get {
                return ResourceManager.GetString("YourFoldersAreBeingRestored", resourceCulture);
            }
        }
    }
}
